import test from 'node:test'
import assert from 'node:assert/strict'
import { deleteSelection, floorClipboard, pasteFloorClipboard, selectionBox, selectionInWorkspace } from './cadEdit.js'
import { cableSpan, deviceTagError } from './deviceTags.js'
import { addWall, detectRooms, drawRoom, emptyPlan, exampleHouse } from './floorplan.js'
import { normalizePlan } from './projects.js'
import { climateOf } from './places.js'
import {
  addServiceNode,
  addServiceRun,
  applyHeating,
  applyLocation,
  deleteServiceNode,
  ensureServices,
  refreshHeat,
  removeAutoAdded,
  rewireHeat,
  updateServiceNode,
} from './services.js'
import { WORKSPACES, applyWorkspaceSwitch } from './workspaces.js'

function counts(plan) {
  const services = plan?.services
  return {
    nodes: services?.nodes?.length || 0,
    runs: services?.runs?.length || 0,
  }
}

function outline() {
  let plan = emptyPlan('Tyhjä')
  const corners = [[0, 0], [12, 0], [12, 9], [0, 9], [0, 0]]
  for (let i = 0; i < corners.length - 1; i += 1) {
    plan = addWall(plan, { x: corners[i][0], z: corners[i][1] }, { x: corners[i + 1][0], z: corners[i + 1][1] }, 'exterior')
  }
  return plan
}

test('a blank outline gains no devices when the place, zone, country or workspace changes', () => {
  let plan = outline()
  assert.equal(counts(plan).nodes, 0)
  assert.equal(counts(plan).runs, 0)
  plan = refreshHeat(plan)
  plan = applyLocation(plan, 'FI', 'helsinki')
  assert.equal(plan.place, 'helsinki')
  assert.equal(climateOf(plan).zone, 'I')
  assert.ok(climateOf(plan).degreeDays > 0)
  plan = refreshHeat({ ...plan, place: null, thermal: { ...(plan.thermal || {}), zone: 'IV', place: '' } })
  assert.equal(climateOf(plan).zone, 'IV')
  plan = applyLocation(plan, 'SE', 'kiruna')
  assert.equal(plan.country, 'SE')
  assert.equal(plan.heating?.source, 'air-water')
  plan = applyLocation(plan, 'ES', 'sevilla')
  assert.equal(plan.heating?.source, 'direct-electric')
  plan = applyHeating(plan, { source: 'ground', distribution: 'floor', borehole: true })
  plan = drawRoom(plan, [{ x: 1, z: 1 }, { x: 5, z: 1 }, { x: 5, z: 4 }, { x: 1, z: 4 }], { name: 'Huone', type: 'huone' })
  plan = refreshHeat(plan)
  for (const workspace of WORKSPACES) {
    plan = applyWorkspaceSwitch(plan, workspace.id)
  }
  const loaded = {
    ...normalizePlan({ name: plan.name, walls: plan.walls, rooms: [], country: plan.country, place: plan.place, thermal: plan.thermal, heating: plan.heating }),
    services: ensureServices({}),
    rooms: detectRooms(plan.walls, []),
  }
  assert.equal(counts(plan).nodes, 0)
  assert.equal(counts(plan).runs, 0)
  assert.equal(counts(loaded).nodes, 0)
  assert.equal(counts(loaded).runs, 0)
  assert.equal(loaded.services.nodes.length, 0)
  assert.equal(loaded.services.runs.length, 0)
})

test('remove auto-added devices and routes in one step and keep a device the user placed', () => {
  const generated = rewireHeat(applyHeating(exampleHouse(), { source: 'district', distribution: 'floor', buffer: false }))
  assert.ok(generated.services.nodes.some((node) => node.auto || node.autoGenerated))
  assert.ok(generated.services.nodes.some((node) => node.kind === 'panel' || node.kind === 'heatpump' || node.kind === 'heat-source'))
  assert.ok(generated.services.runs.length > 0)
  const cleaned = removeAutoAdded(generated)
  assert.equal(cleaned.services.nodes.length, 0)
  assert.equal(cleaned.services.runs.length, 0)
  const placed = {
    ...cleaned,
    services: {
      ...cleaned.services,
      nodes: [{ id: 'socket-1', system: 'electric', kind: 'socket', userPlaced: true, x: 2, z: 2 }],
      runs: [{ id: 'wire-1', system: 'electric', kind: 'wire', manual: true, locked: true, points: [{ x: 0, z: 0 }, { x: 1, z: 0 }] }],
    },
  }
  const kept = removeAutoAdded(placed)
  assert.equal(kept.services.nodes.length, 1)
  assert.equal(kept.services.nodes[0].id, 'socket-1')
  assert.equal(kept.services.runs.length, 1)
  assert.equal(kept.services.runs[0].id, 'wire-1')
})

test('one thermostat stays one, and deleting it does not bring it back', () => {
  let plan = addServiceNode(emptyPlan('LVI'), { system: 'heat', kind: 'thermostat', name: 'Termostaatti', x: 2, z: 2 })
  assert.equal(plan.services.nodes.length, 1)
  assert.equal(plan.services.runs.length, 0)
  assert.equal(plan.services.nodes[0].tag, 'T1')
  const again = addServiceNode(plan, { system: 'heat', kind: 'thermostat', x: 2.03, z: 2.02 })
  assert.equal(again, plan)
  plan = deleteServiceNode(plan, plan.services.nodes[0].id)
  assert.equal(plan.services.nodes.length, 0)
  plan = refreshHeat(plan)
  plan = applyWorkspaceSwitch(plan, 'lvi')
  plan = applyWorkspaceSwitch(plan, 'sahko')
  plan = applyLocation(plan, 'FI', 'helsinki')
  assert.equal(ensureServices(plan).nodes.length, 0)
  assert.equal(ensureServices(plan).runs.length, 0)
})

test('a workspace window selection deletes every device in one step', () => {
  let plan = emptyPlan('Valinta')
  for (let i = 0; i < 10; i += 1) {
    plan = addServiceNode(plan, { system: 'heat', kind: 'thermostat', x: 0.5 + i * 0.4, z: 1.2 })
  }
  plan = addServiceNode(plan, { system: 'electric', kind: 'socket', x: 1, z: 4 })
  assert.equal(plan.services.nodes.filter((node) => node.kind === 'thermostat').length, 10)
  const box = selectionBox({ x: 0, z: 0.4 }, { x: 5, z: 2 })
  assert.equal(box.mode, 'window')
  const hits = selectionInWorkspace(plan, 'lvi', box)
  assert.equal(hits.length, 10)
  assert.equal(hits.every((hit) => hit.kind === 'node'), true)
  plan = deleteSelection(plan, hits)
  assert.equal(plan.services.nodes.filter((node) => node.kind === 'thermostat').length, 0)
  assert.equal(plan.services.nodes.some((node) => node.kind === 'socket'), true)
  const crossing = selectionBox({ x: 3, z: 0 }, { x: 0.2, z: 2 })
  assert.equal(crossing.mode, 'crossing')
})

test('device tags stay unique after create, copy and load', () => {
  let plan = emptyPlan('Tunnukset')
  plan = addServiceNode(plan, { system: 'electric', kind: 'panel', x: 1, z: 1, name: 'Sähkökeskus' })
  plan = addServiceNode(plan, { system: 'electric', kind: 'panel', x: 1, z: 3, name: 'Pääkeskus', role: 'main' })
  plan = addServiceNode(plan, { system: 'electric', kind: 'junction', x: 1.4, z: 1 })
  plan = addServiceNode(plan, { system: 'electric', kind: 'light', x: 3, z: 1 })
  plan = addServiceNode(plan, { system: 'electric', kind: 'socket', x: 4, z: 1 })
  plan = addServiceNode(plan, { system: 'iv', kind: 'ahu', x: 5, z: 1 })
  plan = addServiceNode(plan, { system: 'iv', kind: 'valve', role: 'tulo', x: 5, z: 2 })
  plan = addServiceNode(plan, { system: 'iv', kind: 'valve', role: 'poisto', x: 5, z: 3 })
  plan = addServiceNode(plan, { system: 'water', kind: 'manifold', x: 6, z: 1 })
  plan = addServiceNode(plan, { system: 'drain', kind: 'floor-drain', x: 6, z: 2 })
  plan = addServiceNode(plan, { system: 'heat', kind: 'thermostat', x: 7, z: 1 })
  const byKind = (kind, role) => plan.services.nodes.find((node) => node.kind === kind && (!role || node.role === role))
  assert.equal(byKind('panel').tag, 'SK1')
  assert.equal(byKind('panel', 'main').tag, 'PK1')
  assert.equal(byKind('junction').tag, 'JR1')
  assert.equal(byKind('light').tag, 'V1')
  assert.equal(byKind('socket').tag, 'P1')
  assert.equal(byKind('ahu').tag, 'IV1')
  assert.equal(byKind('valve', 'tulo').tag, 'TU1')
  assert.equal(byKind('valve', 'poisto').tag, 'PO1')
  assert.equal(byKind('manifold').tag, 'JT1')
  assert.equal(byKind('floor-drain').tag, 'K1')
  assert.equal(byKind('thermostat').tag, 'T1')
  const second = addServiceNode(plan, { system: 'electric', kind: 'junction', x: 2, z: 3 })
  assert.equal(second.services.nodes.filter((node) => node.kind === 'junction').map((node) => node.tag).sort().join(','), 'JR1,JR2')
  const rejected = updateServiceNode(second, byKind('thermostat').id, { tag: 'SK1' })
  assert.equal(rejected.services.nodes.find((node) => node.kind === 'thermostat').tag, 'T1')
  assert.match(deviceTagError(second.services.nodes, byKind('thermostat').id, 'SK1'), /jo käytössä/)
  const picks = second.services.nodes.map((node) => ({ kind: 'node', id: node.id }))
  const clip = floorClipboard(second, picks)
  const pasted = pasteFloorClipboard(second, clip, { x: clip.origin.x + 3, z: clip.origin.z + 3 })
  const bare = {
    ...pasted,
    services: {
      ...pasted.services,
      nodes: pasted.services.nodes.map((node, index) => ({ ...node, tag: index === 0 ? 'SK1' : '' })),
    },
  }
  const loaded = normalizePlan(bare)
  const tags = loaded.services.nodes.map((node) => node.tag)
  assert.equal(new Set(tags).size, tags.length)
  assert.equal(tags.every((tag) => /^[A-ZÅÄÖ]+\d+$/.test(tag)), true)
  const panel = loaded.services.nodes.find((node) => node.kind === 'panel' && node.role !== 'main')
  const junction = loaded.services.nodes.find((node) => node.kind === 'junction')
  const wired = addServiceRun(loaded, {
    system: 'electric',
    kind: 'wire',
    points: [{ x: panel.x, z: panel.z }, { x: junction.x, z: junction.z }],
    deviceId: junction.id,
  })
  const run = wired.services.runs[wired.services.runs.length - 1]
  assert.equal(cableSpan(wired.services.nodes, run), `${panel.tag} → ${junction.tag}`)
})
