import test from 'node:test'
import assert from 'node:assert/strict'
import { addWall, detectRooms, drawRoom, emptyPlan, exampleHouse } from './floorplan.js'
import { normalizePlan } from './projects.js'
import { climateOf } from './places.js'
import {
  applyHeating,
  applyLocation,
  ensureServices,
  refreshHeat,
  removeAutoAdded,
  rewireHeat,
} from './services.js'
import { WORKSPACES, applyWorkspaceSwitch } from './workspaces.js'

function counts(plan) {
  const services = plan?.services
  return {
    nodes: services?.nodes?.length || 0,
    runs: services?.runs?.length || 0,
  }
}

function outline() {
  let plan = emptyPlan('Tyhjä')
  const corners = [[0, 0], [12, 0], [12, 9], [0, 9], [0, 0]]
  for (let i = 0; i < corners.length - 1; i += 1) {
    plan = addWall(plan, { x: corners[i][0], z: corners[i][1] }, { x: corners[i + 1][0], z: corners[i + 1][1] }, 'exterior')
  }
  return plan
}

test('a blank outline gains no devices when the place, zone, country or workspace changes', () => {
  let plan = outline()
  assert.equal(counts(plan).nodes, 0)
  assert.equal(counts(plan).runs, 0)
  plan = refreshHeat(plan)
  plan = applyLocation(plan, 'FI', 'helsinki')
  assert.equal(plan.place, 'helsinki')
  assert.equal(climateOf(plan).zone, 'I')
  assert.ok(climateOf(plan).degreeDays > 0)
  plan = refreshHeat({ ...plan, place: null, thermal: { ...(plan.thermal || {}), zone: 'IV', place: '' } })
  assert.equal(climateOf(plan).zone, 'IV')
  plan = applyLocation(plan, 'SE', 'kiruna')
  assert.equal(plan.country, 'SE')
  assert.equal(plan.heating?.source, 'air-water')
  plan = applyLocation(plan, 'ES', 'sevilla')
  assert.equal(plan.heating?.source, 'direct-electric')
  plan = applyHeating(plan, { source: 'ground', distribution: 'floor', borehole: true })
  plan = drawRoom(plan, [{ x: 1, z: 1 }, { x: 5, z: 1 }, { x: 5, z: 4 }, { x: 1, z: 4 }], { name: 'Huone', type: 'huone' })
  plan = refreshHeat(plan)
  for (const workspace of WORKSPACES) {
    plan = applyWorkspaceSwitch(plan, workspace.id)
  }
  const loaded = {
    ...normalizePlan({ name: plan.name, walls: plan.walls, rooms: [], country: plan.country, place: plan.place, thermal: plan.thermal, heating: plan.heating }),
    services: ensureServices({}),
    rooms: detectRooms(plan.walls, []),
  }
  assert.equal(counts(plan).nodes, 0)
  assert.equal(counts(plan).runs, 0)
  assert.equal(counts(loaded).nodes, 0)
  assert.equal(counts(loaded).runs, 0)
  assert.equal(loaded.services.nodes.length, 0)
  assert.equal(loaded.services.runs.length, 0)
})

test('remove auto-added devices and routes in one step and keep a device the user placed', () => {
  const generated = rewireHeat(applyHeating(exampleHouse(), { source: 'district', distribution: 'floor', buffer: false }))
  assert.ok(generated.services.nodes.some((node) => node.auto || node.autoGenerated))
  assert.ok(generated.services.nodes.some((node) => node.kind === 'panel' || node.kind === 'heatpump' || node.kind === 'heat-source'))
  assert.ok(generated.services.runs.length > 0)
  const cleaned = removeAutoAdded(generated)
  assert.equal(cleaned.services.nodes.length, 0)
  assert.equal(cleaned.services.runs.length, 0)
  const placed = {
    ...cleaned,
    services: {
      ...cleaned.services,
      nodes: [{ id: 'socket-1', system: 'electric', kind: 'socket', userPlaced: true, x: 2, z: 2 }],
      runs: [{ id: 'wire-1', system: 'electric', kind: 'wire', manual: true, locked: true, points: [{ x: 0, z: 0 }, { x: 1, z: 0 }] }],
    },
  }
  const kept = removeAutoAdded(placed)
  assert.equal(kept.services.nodes.length, 1)
  assert.equal(kept.services.nodes[0].id, 'socket-1')
  assert.equal(kept.services.runs.length, 1)
  assert.equal(kept.services.runs[0].id, 'wire-1')
})
